notifications:
  email: false

language: node_js

node_js:
  - 'node'

script:
  - yarn lint
  - yarn test && yarn coverage

after_success:
  - yarn add --dev coveralls
  - cat coverage/lcov.info | yarn run coveralls
